test_ssh_connection:
  stage: test
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client bash
  script:
    - echo "Probando conexión SSH..."
    - mkdir -p .ssh
    - cp "$SSH_KEY" .ssh/id_rsa
    - chmod 600 .ssh/id_rsa
    - ssh-keyscan -H 24.199.119.98 >> .ssh/known_hosts
    - ssh -vvv -i .ssh/id_rsa -o StrictHostKeyChecking=yes root@24.199.119.98 "echo 'Conexión SSH exitosa!'"
  only:
    - main
