variables:
  UV_VERSION: "0.5"
  PYTHON_VERSION: "3.11"
  BASE_LAYER: bookworm-slim
  UV_LINK_MODE: copy
  IMAGE_NAME: stevensbohorquez/latvision-app
  IMAGE_TAG: latvision-application-v1.0

stages:
  - test
  - build
  - deploy

run_test:
  stage: test
  image: ghcr.io/astral-sh/uv:$UV_VERSION-python$PYTHON_VERSION-$BASE_LAYER
  before_script:
    - apt-get update && apt-get install -y make libgl1 libglib2.0-0
  script:
    - make test-all
  cache:
    key:
      files:
        - requirements.txt
    paths:
      - venv/

build_image:
  stage: build
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  image: docker:28.5.1-cli
  services:
    - docker:28.5.1-dind
  before_script:
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG -f docker/Dockerfile .
    - docker push $IMAGE_NAME:$IMAGE_TAG

deploy:
  stage: deploy
  script:
    - echo "NOTHING"